<?php
		$vString .= "<th> Id</th>";
		$vString .= "<th>Kli&#235;nt<br>Afleweringsadres</th>";
		$vString .= "<th>Verwysing&nbsp;&nbsp;<br>GRAF/*</th>";
		$vString .= "<th>Boeke&nbsp;&nbsp;&nbsp;</th>";
		$vString .= "<th>Bestel datum</th>";
		$vString .= "<th>Koerier tipe</th>";
		$vString .= "<th>Prys&nbsp;</th>";
		$vString .= "<th>Koerier koste</th>";
		$vString .= "<th>Totale prys&nbsp;&nbsp;</th>";
		$vString .= "<th>Betaling tipe</th>";
		$vString .= "<th>Boodskap</th>";
		$vString .= "<th>Betaal&nbsp;</th>";
		$vString .= "<th>Settled&nbsp;</th>";
		$vString .= "<th>Gereed<br>vir<br>versending</th>";
		$vString .= "<th>Versend<br>Naspoorno.</th>";
		$vString .= "<th>Afgehandel</th>";
		$vString .= "<th>Nota</th>";
		$vString .= "<th></th>";